INSERT INTO CATALOG (PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
    VALUES ('CATALOG-001', 'AAA', 100, 1500);
INSERT INTO CATALOG (PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
    VALUES ('CATALOG-002', 'BBB', 110, 1000);
INSERT INTO CATALOG (PRODUCT_ID, PRODUCT_NAME, STOCK, UNIT_PRICE)
    VALUES ('CATALOG-003', 'CCC', 120, 2000);